# Generated by Django 5.1.2 on 2024-10-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoporteN1",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("instruction", models.TextField()),
                ("categoria", models.TextField()),
                ("intent", models.TextField()),
                ("response", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
